source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘14.0’
use_frameworks!

target “GorillaLogicTest” do
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'RxSwift'
    pod 'RxCocoa'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
